config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :memories
  end

  resources :sessions
  resources :share
  get '/' => 'welcome#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post "/users/:user_id/memberships" => "memberships#create"
  root "welcome#index"
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user, :class_name => "User"
  belongs_to :family, :class_name => "User", :foreign_key => "family_id"

end

app/models/memory.rb
class Memory < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :memories
  has_many :memberships
  has_many :families, :through => :memberships, :dependent => :destroy

  validates :password, confirmation: true

  def add_family(member)
    self_member = Membership.new(user_id: self.id, family_id: member.id)
    if self_member.save
      p "User to New member DONE!"
    end
    member_self = Membership.new(user_id: member.id, family_id: self.id)
    if member_self.save
      p "Member Can see User DONE!"
    end
  end

  def remove_family(member)
    self_member = Membership.find_by(user_id: self.id, family_id: member.id)
    if self_member.delete
      p "Remove User to Family Member"
    end
    member_self = Membership.find_by(user_id: member.id, family_id: self.id)
    if member_self.delete
      p "Remove Family Member to User"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  def create
    @user = User.find_by(id: params[:user_id])
    if @family = family = User.find_by(email: params[:email])
      Membership.create(user_id: @user.id, family_id: family.id)
      Membership.create(user_id: family.id, family_id: @user.id)
      redirect_to @user
    else
      redirect_to @user
    end
  end

end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /memories
  # GET /memories.json
  def index
    @user = User.find_by(id: session[:id])
    @memories = @user.memories
  end

  # GET /memories/1
  # GET /memories/1.json
  def show
    @user = User.find_by(id: params[:user_id])
    @memory = Memory.find_by(id: params[:id])
  end

  # GET /memories/new
  def new
    binding.pry
    @user = User.find_by(id: session[:id])
    @memory = @user.memories.new
  end

  # GET /memories/1/edit
  def edit

    @user = User.find_by(id: params[:user_id])
    @memory = Memory.find_by(id: params[:id])
    @memories = @user.memories
    # @memory.update(memory_params)
    # redirect_to user_memories
  end

  # POST /memories
  # POST /memories.json
  def create
    @user = User.find_by(id: params[:user_id])
    @memory = Memory.new(memory_params)
    @memory.user_id = @user.id
    respond_to do |format|
      if @memory.save
        format.html { redirect_to user_path(@user), notice: 'memory was successfully created.' }
        format.json { render :show, status: :created, location: @memory }
      else
        format.html { render :new }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memories/1
  # PATCH/PUT /memories/1.json
  def update
    @memory = Memory.find_by(id: params[:id])
    @user = User.find_by(id: params[:user_id])
    respond_to do |format|
      if @memory.update(memory_params)
        format.html { redirect_to user_path(@user), notice: 'memory was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory }
      else
        format.html { render :edit }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memories/1
  # DELETE /memories/1.json
  def destroy
    @user = User.find_by(id: params[:user_id])
    @memory = Memory.find_by(id: params[:id])
    @memory.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'memory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_memory
    if @memory
      @memory = Memory.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def memory_params
    params.require(:memory).permit(:title, :url, :description, :story, :private)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # protect_from_forgery with: :reset_session
  def show
  end

  def create
    @user = User.find_by(email: params[:user][:email].downcase)

    if @user && @user.authenticate(params[:user][:password])
      session[:id] = @user.id
      redirect_to @user
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:id] = nil
    redirect_to root_path
  end
end

app/controllers/share_controller.rb
class ShareController < ApplicationController
  include ApplicationHelper

  def create
    @user = current_user
    old_memory = Memory.find_by(id: params[:format])
    @memory = Memory.new(title: old_memory.title, url: old_memory.url, description: old_memory.description, story: old_memory.story, private: old_memory.private, user_id: @user.id)
    if @memory.save
      redirect_to user_path(current_user.id)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # protect_from_forgery with: :reset_session
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by(id: params[:id])
    @memories = @user.memories
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    if @user
      @user = User.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:id] != nil
      @user = User.find_by(id: session[:id])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rituals
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Tangerine", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=La+Belle+Aurore", :rel => "stylesheet", :type => "text/css"}/
    %meta{:content => "width = 1050, user-scalable = no", :name => "viewport"}/
    /
      \// <script type="text/javascript" src="../../extras/jquery.min.1.7.js"></script>
      \// <script type="text/javascript" src="../../extras/modernizr.2.5.3.min.js"></script>
    / Animation CSS
    %link{:href => "https://cdn.jsdelivr.net/animatecss/3.5.1/animate.css", :rel => "stylesheet"}/
    / Custom Fonts
    / <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    %link{:href => "http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Montserrat:400,700", :rel => "stylesheet", :type => "text/css"}/
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    / Navigation
    %nav.navbar.navbar-custom.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-main-collapse", "data-toggle" => "collapse", :type => "button"}
            %i.fa.fa-bars
        .collapse.navbar-collapse.navbar-right.navbar-main-collapse
          %ul.nav.navbar-nav
            / Hidden li included to remove active class from login link when scrolled up past login section
            - if @user.email && @user.id
              %li.hidden
                %a{:href => "#page-top"}
              %li
                = link_to "Home", user_path(@user), :class => "gray_text"
              %li.center
                Memories
                %span.badge
                  = @memories.count
              - if session[:id] && @memories.count > 0 && session[:id].to_s === params[:id].to_s
                %li
                  %a.gray_text{"data-target" => "#new-memory-modal", "data-toggle" => "modal", :href => "#", :role => "button"} Create a Memory
                %li
                  %a.gray_text{"data-target" => "#family-modal", "data-toggle" => "modal", :href => "#", :role => "button"}
                    Family Members
                    %span.badge
                      = @user.families.count
                %li
                  %a.gray_text{"data-target" => "#new-member-modal", "data-toggle" => "modal", :href => "#", :role => "button"} Add A Family Member
              - elsif session[:id] && @memories.count == 0 && session[:id].to_s === params[:id].to_s
                %li
                  %a.gray_text.animated.infinite.bounce{"data-target" => "#new-memory-modal", "data-toggle" => "modal", :href => "#", :role => "button"} Create a Memory
                %li
                  %a.gray_text{"data-target" => "#family-modal", "data-toggle" => "modal", :href => "#", :role => "button"}
                    Family Members
                    %span.badge
                      = @user.families.count
                %li
                  %a.gray_text{"data-target" => "#new-member-modal", "data-toggle" => "modal", :href => "#", :role => "button"} Add A Family Member
              %li{:style => "color:white"}
                = link_to 'Logout', session_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, :class => "gray_text"
            - else
              %li.hidden
                %a{:href => "#page-top"}
              %li
                %a.page-scroll{:href => "#login", :style => "text-transform: capitalize;"} Login
              %li
                %a.page-scroll{:href => ".download-section", :style => "text-transform: capitalize;"} Sign Up
        / /.navbar-collapse
      / /.container
    = yield

app/views/memberships/_membership.html.erb
<li><a href="/users/<%= @family.id %>"><%= @family.first_name %></a></li>

app/views/memberships/index.html.erb
index

app/views/memories/_new_memory.html.erb
<div class='page-wrapper'>
  <div>
    <h1> Story </h1>
    <p><%= @memory.story %></p>
  </div>
  <div>
    <h1> <%= @memory.title.capitalize %></h1>
    <br>
    <% if @memory.url %>
        Url: <img src="<%= @memory.url %>" alt="image of story">
    <% end %>
    <br>
    Description: <p><%= @memory.description %></p>
    <br>
    <td><%= link_to 'Edit', edit_user_memory_path(@user, @memory) %></td>
    <td><%= link_to 'Remove', user_memory_path(@user, @memory), method: :delete, data: {confirm: 'Are you sure?'} %></td>
  </div>
</div>

app/views/memories/edit.html.erb
<h1>Editing Memory</h1>

<%= render 'form' %>

<%= link_to 'Show', user_memories_path(@memory) %> |
<%= link_to 'Back', user_memories_path %>

app/views/memories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Memories</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Description</th>
    <th>Story</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @memories.each do |memory| %>
      <tr>
        <td><%= memory.title %></td>
        <td><%= memory.url %></td>
        <td><%= memory.description %></td>
        <td><%= memory.story %></td>

        <td><%= link_to 'Show', user_memory_path(@user, memory) %></td>
        <td><%= link_to 'Edit', edit_user_memory_path(@user, memory) %></td>
        <td><%= link_to 'Destroy', user_memory_path(@user, memory), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memory', new_user_memory_path %>

app/views/memories/new.html.erb
<h1>New Memory</h1>




<title>Title of the document</title>
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.0.min.js"></script>
<script src="../../assets/javascripts/memorymodal.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="../../assets/stylesheets/memorymodal.css">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>
<div class="container">
  <div class="row">
    <h1 class="text-center">Modal Login with jQuery Effects</h1>
    <p class="text-center">
      <a href="#" class="btn btn-primary btn-lg" role="button" data-toggle="modal" data-target="#login-modal">Open Login
        Modal</a></p>
  </div>
</div>
<!-- END # BOOTSNIP INFO -->

<!-- BEGIN # MODAL LOGIN -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" align="center">
        <img class="img-circle" id="img_logo" src="https://usmansami.files.wordpress.com/2015/08/cdsffgmfsd.jpg">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </button>
      </div>

      <!-- Begin # DIV Form -->
      <div id="div-forms">

        <!-- Begin # Login Form -->
        <form id="login-form">
          <div class="modal-body">
            <div id="div-login-msg">


            </div>
            <div class="form-group">
              <label for='login_username'>Title of Your Memory: </label>
              <input class="form-control" type='text' name='memory[title]'>
            </div>

            <div class="form-group">
              <label for='description'>URL: </label>
              <input class="form-control" type='text' name='item[description]'>
            </div>

            <div class="form-group">
              <label for='start_date'>Description: </label>
              <input class="form-control" type='textarea' name='item[start_date]'>
            </div>
            <label for='story'>Story: </label>
            <br>
            <textarea cols="40" rows="5" name="story">
Tell Your Story
</textarea>
            <br>
            <label for="login_password">Security</label><br>

            <input id="login_password" class="form-control" type="text" placeholder="Public/Private" required>

          </div>
      </div>
      <div class="modal-footer">
        <div>
          <button type="submit" class="btn btn-primary btn-lg btn-block">Create Memory</button>
        </div>
        </form>
        <!-- End # Login Form -->

        <!-- Begin | Lost Password Form -->

      </div>
      <!-- End # DIV Form -->

    </div>
  </div>
</div>
</body>









<%= link_to 'Back', user_memories_path %>

app/views/memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @memory.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @memory.url %>
</p>

<p>
  <strong>Description</strong>
  <%= @memory.description %>
</p>

<p>
  <strong>Story:</strong>
  <%= @memory.story %>
</p>

<%= link_to 'Edit', edit_user_memory_path(@user.id, @memory) %> |
<%= link_to 'Back', user_memories_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="flipbook-viewport">
  <div class="container">
    <div class="flipbook">
      <div>
      <h1> Users</h1>
      </div>

      <div>
      <h2> </h2>
      </div>
      <div>

      <p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Password</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
      </div>

    </div>
  </div>
</div>


<script type="text/javascript">

function loadApp() {

  // Create the flipbook

  $('.flipbook').turn({
      // Width

      width:922,

      // Height

      height:600,

      // Elevation

      elevation: 50,

      // Enable gradients

      gradients: true,

      // Auto center this flipbook

      autoCenter: true

  });
}

// Load the HTML4 version if there's not CSS transform

yepnope({
  test : Modernizr.csstransforms,
  // yep: ['../../lib/turn.js'],
  // nope: ['../../lib/turn.html4.min.js'],
  // both: ['css/basic.css'],
  complete: loadApp
});

</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="backgrounding">
      <!-- BEGIN # MODAL Create a Memory -->
      <div class="modal fade" id="new-memory-modal" tabindex="-1" role="dialog" aria labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
          <div class="modal-content "  style="background-color: black">


              <button type="button" class="close" data-dismiss="modal" aria-label="Close">

              </button>


            <div id="div-forms">
              <form action="/users/<%= @user.id %>/memories" method="post" id="login-form">
                <div class="modal-body">
                  <div id="div-login-msg">
                  </div>
                  <div class="form-group">
                    <label for='login_username' style="text-align: center; display: block; color: white; font-family: 'Tangerine', cursive; font-size: 30px">Title of Your Memory </label>
                    <input class="form-control" type='text' name='memory[title]'>
                  </div>

                  <div class="form-group">
                    <label for='description'  style="text-align: center; display: block; color: white; font-family: 'Tangerine', cursive; font-size: 30px">URL </label>
                    <input class="form-control" type='text' name='memory[url]'>
                  </div>

                  <div class="form-group">
                    <label for='start_date'  style="text-align: center; display: block; color: white; font-family: 'Tangerine', cursive; font-size: 30px">Description </label>
                    <input class="form-control" type='textarea' name='memory[description]'>
                  </div>
                  <div>
                    <label for='story'  style="text-align: center; display: block; color: white; font-family: 'Tangerine', cursive; font-size: 30px">Story </label><br>
                    <textarea cols="50" rows="10" name="memory[story]" text-align="left"></textarea>
                    <br>
                    <label for="private?"  style="text-align: center; display: block; color: white; font-family: 'Tangerine', cursive; font-size: 30px">Privacy </label>
                    <input class="secure" type="radio" name="memory[private]" value="true" checked >
                    <label style="color:white">Private</label><br>
                    <input type="radio" name="memory[private]" value="false" >
                    <label style="color:white">Public</label>
                    <br>
                  </div>
                </div>
                <div class="modal-footer">
                  <div>
                    <button type="submit" class="btn  btn-lg btn-block modal_text_box" style="color: black; font: 50px Tangerine">Create Memory</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </body>





    <!-- BEGIN # MODAL Family -->
    <div class="modal fade" id="family-modal" tabindex="-1" role="dialog" aria labelledby="myModalLabel" aria-hidden="true" >

      <div class="modal-dialog">
        <div class="modal-content" style="background-color: black">

          <div class="modal-header" align="center">
               <h1 style="color: white; font-family: 'Tangerine', cursive;"> Your Family Members </h1>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">

            </button>
          </div>

          <div id="div-forms">

<% @user.families.each do |family_member| %>
  <div class="col-md-13">
    <div class="list-group-item modal_text_box" ;>
      <a href="/users/<%=family_member.id%>" style="color: black; font-size: 30px; font-family: 'Tangerine', cursive;"> <%=family_member.first_name%></a>
    </div>
  </div>
<% end %>
<div class="modal-footer">

                </div>
          </div>
        </div>
      </div>
    </div>


      <!-- BEGIN # MODAL Add Family Modal -->
    <div class="modal fade" id="new-member-modal" tabindex="-1" role="dialog" aria labelledby="myModalLabel" aria-hidden="true" style="display: none;">
      <div class="modal-dialog">
        <div class="modal-content" style="background-color: black">
          <div class="modal-header" align="center">
           <h1 style="font-size: 50px; color: white; font-family: 'Tangerine', cursive;"> Add Family Member</h1>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">

            </button>
          </div>

          <div id="div-forms">

            <form action="/users/<%= @user.id %>/memberships" method="post" id="new-membership-form">
                <div class="modal-body">
                  <div id="div-login-msg">
                  </div>
                  <div class="form-group">
                    <label for='login_username' style="color: white; font-family: 'Tangerine', cursive; font-size: 30px"  >Email: </label>
                    <input class="form-control" type='text' name='email'>
                  </div>
                </div>
                <div class="modal-footer">
                  <div>
                    <button type="submit" class="btn  btn-lg btn-block modal_text_box" style="color: black; font: 50px Tangerine">Add to Family</button>
                  </div>
                </div>
              </form>

          </div>
        </div>
      </div>
    </div>


<div id="bg">
  <img src="http://wapphouse.xyz/wp-content/uploads/2016/02/dark-wood-background.jpg" alt="">

</div>






  <div class="flipbook-viewport">
    <div class="container">
      <div class="flipbook animated fadeInUpBig">
        <div class="hard book">
          <h1 id="cover" class="indent"><%=@user.first_name.capitalize  + "'s" + " memories"%></h1>
        </div>

        <div class="hard book">
        </div>

        <div class='page-wrapper'>
          <br>
          <p class="indent">Dedicated to the wonderful people in my life</p>
        </div>
          <% @memories.each do |memory| %>
        <div class='page-wrapper'>
          <h1 class="indent"> Story </h1>
          <p class="user-text"><%= memory.story %></p>
        </div>
        <div class="page-wrapper new-memory">
          <h1 class="indent"> <%= memory.title.capitalize %></h1>
          <br>
          <% if memory.url %>
            <p class="indent">
              <iframe width="420" height="315" src="<%= memory.url %>" frameborder="0" allowfullscreen></iframe>
            </p>
          <%end%>
          <br>
          <p class="indent">
          <p class= "user-text"><%= memory.description %></p>
          </p>
          <br>

          <!-- If memory does not belong to user's family member's, they cannot share -->
          <%current_user.families.each do |family_member| %>
            <%if memory.user_id == family_member.id %>
              <p class= "indent">
                <%= link_to 'Share', share_index_path(memory), method: :post %>
              </p>
            <%end%>
          <%end%>


          <!-- If it is not the User's book, no auth for memories -->
          <% if memory.user_id == session[:id] %>
          <p class= "indent">
            <td><%= link_to 'Edit', edit_user_memory_path(@user, memory) %></td>
            <td><%= link_to 'Remove', user_memory_path(@user, memory), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </p>
          <%end%>


        </div>

        <% end %>

        <div class = "paper-wrapper" id='last-page'>
        </div>
        <div class= "book hard">
        </div>
        <div class="book hard">
        </div>

      </div>
    </div>
  </div>


  <script type="text/javascript">

    function loadApp() {

  // Create the flipbook

  $('.flipbook').turn({
      // Width

      width:922,

      // Height

      height:600,

      // Elevation

      elevation: 50,

      // Enable gradients

      gradients: true,

      // Auto center this flipbook

      autoCenter: true

    });
}

// Load the HTML4 version if there's not CSS transform

yepnope({
  test : Modernizr.csstransforms,

  // Tests changed to speed up book
  // yep: ['../../assets/javascripts/turn.js'],
  // nope: ['../../assets/javascripts/turn.html4.min.js'],
  // both: ['../../basic/css/basic.css'],
  complete: loadApp
});

</script>